# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
  - id: cmake-lint
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    args: [-i]
- repo: local
  hooks:
  - id: run-tests
    args: [--output-on-failure,--stop-on-failure,--progress,--preset;ninja-multi]
    entry: ctest
    language: system
    name: Run tests
    stages: [pre-commit]
